# Generated by Django 3.0.2 on 2020-03-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='título del mensaje', max_length=50)),
                ('Message', models.TextField(help_text='Que esta en tu mente ... ')),
            ],
        ),
    ]
