# Generated by Django 3.0.2 on 2020-03-20 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Message',
            new_name='message',
        ),
    ]
